language: python
sudo: false
env:
  - TOXENV=py27
addons:
  apt:
    packages:
    - libgmp3-dev
install:
  - pip install tox
  - pip install coveralls
script: tox -- --ignore hydrachain/tests/test_sim_failures.py --ignore hydrachain/tests/test_sim_syncing.py
after_success: coveralls
deploy:
  provider: pypi
  user: ethereum_pypi_automated
  password:
    secure: "vO6kAkkpdqQz2+Le7aowcIkYHyvQzuNaL35c8ciHzmT2VdeGeCsDBGyJ8RYqITQruwfVzUsKsNjfCXBTcYan3e1vPpG9KKrkxB/Zy6KcNJmd+SL9n2tB6TVFr1ojxnRJgIzFBxbA1FnyY0aodwnMW2bJBlKxFIKJiKVjK6GGDl11wrMsudFFnvs3LkrPO9tr1plmN1xvVTNLzy0UmHjx6lmtjtZ/HMbx635WnFj5NnzdeMK07XD59HEuOYVvQ7BQua2cuCevFbXmSAxHJsDPZuhzYHkEfj+jPhKbS1MyTqD5W72ex2oPRmPlvvnOn01750IkSFSyO0lnZIv1wJuZ3+Y+49Q5XrFBAsuC4bqk1uOVL5hU37b2oDBIunJLQYEP1tn7TibVbv51iOolzx193tRR7KcbyU+pIqdP4a6rWDXT+PRada2JemX/Bx4G5hn9dXc4SmLP0+t7lcYpe/fTLQCGYsLNBbJv7iJdTuOeySX8Dlq9GYBMGreilDwIp5T4eqT4mhc25ZaXRel2HdqQSzie8SM88Sempn1V3uQkvQSUZ/PcwDwrG8wLK37BubaW0qVAZ5Zfkv1Q+pnVd7OkTEU+GgdOST6H3WGKVSO0fs/vLFYhQN0273IqM3Uuh3+s5h/sbGWfXqPMS8lu6febpglBCAxvkgKjwQ0in2S3Fo8="
  on:
    tags: true
    repo: HydraChain/hydrachain
    branch: develop
  distributions: "sdist bdist_wheel"
